# Generated by Django 4.2 on 2025-07-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_inboxemail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxemail',
            name='user',
        ),
    ]
