# Generated by Django 4.2 on 2025-07-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0005_delete_inboxemail_alter_email_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_type',
            field=models.CharField(choices=[('sent', 'Sent'), ('received', 'Received'), ('uploaded', 'Uploaded')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
