# Generated by Django 4.2 on 2025-07-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_email_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Sent'), (2, 'Compose'), (3, 'Upload_eml')], default=0),
        ),
    ]
