# Generated by Django 4.2 on 2025-07-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0008_alter_email_email_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_type',
        ),
    ]
