# Generated by Django 4.2 on 2025-07-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_remove_email_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Upload_eml')], default=0),
        ),
    ]
