# Generated by Django 4.2 on 2025-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0011_alter_email_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='bcc',
            field=models.TextField(blank=True, db_comment='Blind carbon copy (BCC) recipient email addresses, comma-separated (not visible to other recipients', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='cc',
            field=models.TextField(blank=True, db_comment='Carbon copy (CC) recipient email addresses, comma-separated.', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(db_comment='Email address from which the email was sent', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.TextField(db_comment='Recipients email address'),
        ),
    ]
