# Generated by Django 4.2 on 2025-07-21 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0012_alter_email_bcc_alter_email_cc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='body_html',
            field=models.TextField(blank=True, db_comment='Html content of an email body', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='body_plain',
            field=models.TextField(blank=True, db_comment='Plain text content of an email body', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Upload_eml')], db_comment='Categories of email', default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(db_comment='Subject line of email', max_length=255),
        ),
        migrations.AlterField(
            model_name='email',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_comment='Data / Time when the email record is created or recevied'),
        ),
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(db_comment='Foreign key to the user table who owns this email.', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
