# Generated by Django 4.2 on 2025-07-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0013_alter_email_body_html_alter_email_body_plain_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
        migrations.AlterModelTableComment(
            name='attachment',
            table_comment='Stores details about files attached to email messages.',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(db_comment='Foreign key linking to the email message this attachment belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mail.email'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(db_comment='path to store attached file on server', upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(db_comment='original filename of attached file', max_length=255),
        ),
    ]
