# Generated by Django 4.2 on 2025-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0014_alter_attachment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Upload_eml')], db_comment='Categories of emaillll', default=0),
        ),
    ]
