# Generated by Django 4.2 on 2025-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0015_alter_email_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email_address',
            field=models.EmailField(db_comment='Sender or recipient email address', default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Upload_eml')], db_comment='Categories of emaillll', default=1),
        ),
    ]
