# Generated by Django 4.2 on 2025-07-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0016_email_email_address_alter_email_email_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email_address',
        ),
    ]
