# Generated by Django 4.2 on 2025-07-31 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0017_remove_email_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_read',
            field=models.BooleanField(db_comment='Flag to indicate if the email has been read by the user', default=False),
        ),
    ]
