# Generated by Django 4.2 on 2025-08-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0018_email_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email_type',
            field=models.IntegerField(choices=[(0, 'Inbox'), (1, 'Upload_eml'), (2, 'Sent')], db_comment='Categories of emaillll', default=1),
        ),
    ]
